### ISSUE TITLE
App crashes when segue presentation is Over Full Scren

### ISSUE THREAD

**Issue by aabosh** [yuwang17/WYInteractiveTransitions#2]
Currently using these transitions, but I have ran into one significant issue. When segueing to a storyboard with it's presentation as type _Over Full Screen_, the app crashes with the error:
`fatal error: unexpectedly found nil while unwrapping an Optional value
`

Currently segueing using storyboards and have a prepareForSegue function in my view controller.

```
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if (segue.identifier == "settings") {
            let duration = 0.6
            WYTransitionMgr.configureTransition(duration, toViewController: segue.destinationViewController, handGestureEnable: true, transitionType: .Up)
        }
    }
```

Any help would be appreciated, thanks!

**Comment by Yu-w** [comment]
Gotcha. It seems that when the presentation set to `Over Full Screen`, the function `animateTransition(transitionContext: UIViewControllerContextTransitioning)` no longer can capture the origin view context. I'll fix that, no worry.

**Comment by aabosh** [comment]
Awesome, really appreciate the quick reply! Enjoy your weekend.

**Comment by Yu-w** [comment]
No problem. Just pushed a newer version of pod. Please `pod update` to get latest version.

Thanks for supporting. Have a good weekend too. I'll add another critical update to this library later sometimes (won't affect your current development).
